name: yendoo_app
description: AplicaciÃ³n Yendo desde cero
publish_to: 'none'

version: 1.0.4+9

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Otros paquetes
  fluttertoast: ^8.2.12
  flutter_map: ^8.1.1
  geolocator: ^14.0.2
  latlong2: ^0.9.0
  intl: ^0.20.2           # ðŸ‘ˆ para formatear fechas

  # SONIDO
  audioplayers: ^6.5.1   # ðŸ‘ˆ versiÃ³n nueva para iOS

  # Para AndroidX
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # ðŸ‘ˆ generador de Ã­conos del launcher

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icono_local.png
    - assets/sonidos/notificacion.mp3   # ðŸ‘ˆ agregado correctamente

# ðŸ‘‡ ConfiguraciÃ³n del icono del launcher (Android)
flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 24
  image_path: assets/yendo_icon_1024_bg.png   # ðŸ‘ˆ tu PNG 1024Ã—1024
